'ues strict';

export const Data = [
    { // index 0
        name: 'index',
        element: 'div',
        type: ['id'],
        value: ['index'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // header 1
        name: 'header',
        element: 'header',
        type: [],
        value: [],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // nav 2
        name: 'nav',
        element: 'nav',
        type: [],
        value: [],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // logo 3
        name: 'logo',
        element: 'div',
        type: ['class'],
        value: ['logo'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // words 4
        name: 'words',
        element: 'div',
        type: ['class'],
        value: ['words'],
        text: [],
        number: 4,
        array: [],
        parent: null,
    },

    { // text 5
        name: 'text',
        element: 'span',
        type: ['class'],
        value: ['text'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // container 6
        name: 'container',
        element: 'section',
        type: ['class'],
        value: ['container'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // head 7
        name: 'head',
        element: 'div',
        type: ['class'],
        value: ['head'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // main 8
        name: 'main',
        element: 'main',
        type: [],
        value: [],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // ear 9
        name: 'ear',
        element: 'div',
        type: ['class'],
        value: ['ear'],
        text: [],
        number: 2,
        array: [],
        parent: null,
    },

    { // arm 10
        name: 'arm',
        element: 'div',
        type: ['class'],
        value: ['arm'],
        text: [],
        number: 2,
        array: [],
        parent: null,
    },

    { // lower_body 11
        name: 'lower_body',
        element: 'div',
        type: ['class'],
        value: ['lower_body'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // leg 12
        name: 'leg',
        element: 'div',
        type: ['class'],
        value: ['leg'],
        text: [],
        number: 2,
        array: [],
        parent: null,
    },

    { // tail 13
        name: 'tail',
        element: 'div',
        type: ['class'],
        value: ['tail'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // foot 14
        name: 'foot',
        element: 'div',
        type: ['class'],
        value: ['foot'],
        text: [],
        number: 11,
        array: [],
        parent: null,
    },

    { // sole 15
        name: 'sole',
        element: 'div',
        type: ['class'],
        value: ['sole'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // toe 16
        name: 'toe',
        element: 'div',
        type: ['class'],
        value: ['toe'],
        text: [],
        number: 4,
        array: [],
        parent: null,
    },

    { // foot_print 17
        name: 'foot_print',
        element: 'div',
        type: ['class'],
        value: ['foot_print'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },
    
    { // bottom 18
        name: 'bottom',
        element: 'section',
        type: ['class'],
        value: ['bottom'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // footer 19
        name: 'footer',
        element: 'footer',
        type: [],
        value: [],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },
];