'ues strict';

export const Data = [
    { // index 0
        name: 'index',
        element: 'div',
        type: ['id'],
        value: ['index'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // header 1
        name: 'header',
        element: 'header',
        type: [],
        value: [],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // left 2
        name: 'left',
        element: 'section',
        type: ['class'],
        value: ['left'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // right 3
        name: 'right',
        element: 'section',
        type: ['class'],
        value: ['right'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // logo 4
        name: 'logo',
        element: 'div',
        type: ['class'],
        value: ['logo'],
        text: ['K S G'],
        number: 1,
        array: [],
        parent: null,
    },

    { // menu_wrap 5
        name: 'menu_wrap',
        element: 'ul',
        type: ['class'],
        value: ['menu_wrap'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // menu 6
        name: 'menu',
        element: 'li',
        type: ['class'],
        value: ['menu'],
        text: ['menu1', 'menu2'],
        number: 2,
        array: [],
        parent: null,
    },

    { // option 7
        name: 'option',
        element: 'ul',
        type: ['class'],
        value: ['option'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // item 8
        name: 'item',
        element: 'li',
        type: ['class'],
        value: ['item'],
        text: ['<i class="bi bi-moon-fill"></i>', '<i class="bi bi-github"></i>', '<i class="fa-solid fa-arrow-up-from-bracket"></i>'],
        number: 3,
        array: [],
        parent: null,
    },

    { // bar 9
        name: 'bar',
        element: 'div',
        type: ['class'],
        value: ['bar'],
        text: ['<i class="bi bi-list"></i>'],
        number: 1,
        array: [],
        parent: null,
    },

    { // aside 10
        name: 'aside',
        element: 'aside',
        type: [],
        value: [],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // roof 11
        name: 'roof',
        element: 'section',
        type: ['class'],
        value: ['roof'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // eaves 12
        name: 'eaves',
        element: 'section',
        type: ['class'],
        value: ['eaves'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // container 13
        name: 'container',
        element: 'div',
        type: ['class'],
        value: ['container'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // main 14
        name: 'main',
        element: 'main',
        type: [],
        value: [],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // roof_tile 15
        name: 'roof_tile',
        element: 'div',
        type: ['class'],
        value: ['roof_tile'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // tile 16
        name: 'tile',
        element: 'div',
        type: ['class'],
        value: ['tile'],
        text: [],
        number: 2,
        array: [],
        parent: null,
    },

    { // fade 17
        name: 'fade',
        element: 'section',
        type: ['class'],
        value: ['fade'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // btns 18
        name: 'btns',
        element: 'div',
        type: ['class'],
        value: ['btns'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // prev 19
        name: 'prev',
        element: 'btn',
        type: ['class'],
        value: ['prev'],
        text: ['prev'],
        number: 1,
        array: [],
        parent: null,
    },

    { // next 20
        name: 'next',
        element: 'btn',
        type: ['class'],
        value: ['next'],
        text: ['next'],
        number: 1,
        array: [],
        parent: null,
    },

    { // BG 21
        name: 'BG',
        element: 'div',
        type: ['class'],
        value: ['BG'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },

    { // BG_item 22
        name: 'BG_item',
        element: 'div',
        type: ['class'],
        value: ['BG_item'],
        text: [1, 2 , 3, 4, 5],
        number: 5,
        array: [],
        parent: null,
    },

    { // slider 23
        name: 'slider',
        element: 'section',
        type: ['class'],
        value: ['slider'],
        text: [],
        number: 1,
        array: [],
        parent: null,
    },
    
    { // slider_item 24
        name: 'slider_item',
        element: 'div',
        type: ['class'],
        value: ['slider_item'],
        text: [4, 5, 1, 2, 3, 4, 5, 1, 2],
        number: 9,
        array: [],
        parent: null,
    },
];